version: '3'
services:
  todoapp-backend:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_SERVER: mysql-db
      DB_USER: root
      DB_PASSWORD: test@123
      DB_NAME: todo_db
    depends_on:
      - todoapp-mysql
    networks:
      - todoapp-network
  todoapp-mysql:
    image: mysql:5.7
    container_name: todoapp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_DATABASE: todo_db
    volumes:
      - todoapp-volume:/var/lib/mysql
    networks:
      - todoapp-network
  todoapp-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: todoapp-mysql
      MYSQL_ROOT_PASSWORD: test@123
    depends_on:
      - todoapp-mysql
    networks:
      - todoapp-network
volumes:
  todoapp-volume:
networks:
  todoapp-network:  
