apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todoapp-backend
  labels:
    app: todoapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-backend
  template:
    metadata:
      labels:
        app: todoapp-backend  
    spec:
      containers:
        - name: todoapp-backend
          image: roni313233/todoapp-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_SERVER
              value: "mysql"
            - name: DB_NAME
              value: "todo_db"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: "Test@123"
