apiVersion: apps/v1
kind: Service
metadata:
    name: backend-svc
    labels:
        app: backend
spec:
    selector: 
        app: backend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
          nodePort: 30080
    type: NodePort